apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2022-05-23T09:07:58Z"
  generation: 2
  labels:
    app: animals
  name: animals
  namespace: default
  resourceVersion: "50185"
  uid: 678c1f52-0bc3-45ab-9a51-aba4a2ce231b
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: animals
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: animals
    spec:
      containers:
      - image: supergiantkir/animals:hare
        imagePullPolicy: IfNotPresent
        name: animals
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: "2022-05-23T09:08:06Z"
    lastUpdateTime: "2022-05-23T09:08:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-05-23T09:07:58Z"
    lastUpdateTime: "2022-05-23T09:25:25Z"
    message: ReplicaSet "animals-7d89bf99f7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
