apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: redis 
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: type
            operator: In
            values:
            - sql
        topologyKey: kubernetes.io/hostname
  containers: 
  - name: redis 
    image: supergiantkir/animals:hare
    ports: 
    - containerPort: 80
    label:
      type: redis
    
