apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: web
 labels:
   type: web
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: type
            operator: In
            values:
            - redis
        topologyKey: kubernetes.io/hostname
  containers: 
  - name: web
    image: supergiantkir/animals:moose
    ports: 
    - containerPort: 80
