apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: sql
 labels:
   type: sql
spec:
  containers: 
  - name: sql 
    image: supergiantkir/animals:bear
    ports: 
    - containerPort: 80
